name: MenuSideKick
description: "Menu SideKick"
publish_to: 'none'

version: 3.0.0+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  http: ^1.4.0
  go_router: ^15.1.2
  get: ^4.7.2
  gap: ^3.0.1
  google_fonts: ^6.3.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  camera: ^0.11.1
  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0
  internet_connection_checker_plus: ^2.7.2
  get_it: ^8.0.3
  logger: ^2.5.0
  device_preview: ^1.2.0
  flutter_verification_code: ^1.1.7
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.5
  pdf: ^3.11.3
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  file_picker: ^8.1.4
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  cached_network_image: ^3.4.1

  # âœ… In-App Purchase packages
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+1
  in_app_purchase_storekit: ^0.3.17+1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.14.3

flutter_gen:
  output: lib/core/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path_android: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/